e: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: AsadorDeTelefono-APK
          path: app/build/outputs/apk/debug/app-debug.apk


---

4. Confirmar el archivo

Abajo, presiona el botón que dice “Start commit”

Luego, presiona “Commit new file”



---

Después de eso, GitHub comenzará a compilar la app automáticamente.
Te aviso cómo descargar el APK cuando termine.

¿Listo para pegar el código y hacer commit? ¿Necesitas que te ayude con eso?

